services:
  spring-boot-app:
    image: codedcode
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: jdbc
      MYSQL_ROOT_PASSWORD: D@ngereag1e  # Replace with your actual password
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: {}  # Persist data volume for MySQL